services:

  px4-gazebo:
    build:
      context: ./px4
      dockerfile: Dockerfile
    container_name: px4-gazebo
    stdin_open: true
    tty: true
    depends_on:
      - microxrce-agent

    ports:
      - "14540:14540/udp"
      - "14550:14550/udp"
      - "18570:18570/udp"


    ipc: host
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PX4_UXRCE_DDS_PORT=8888
      - PX4_UXRCE_DDS_AG_IP=microxrce-agent
      - PX4_GZ_WORLD=default
      - PX4_MAKE_TARGET=gz_standard_vtol
      - PX4_GZ_MODELS=/workspace/px4/PX4-Autopilot/Tools/simulation/gz/models
      - PX4_GZ_WORLDS=/workspace/px4/PX4-Autopilot/Tools/simulation/gz/worlds
      - GZ_SIM_RESOURCE_PATH=/workspace/custom_models:/workspace/px4/PX4-Autopilot/Tools/simulation/gz/models:/workspace/px4/PX4-Autopilot/Tools/simulation/gz/worlds
    volumes:
      - ./px4:/workspace/px4
      - ./models:/workspace/custom_models
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000:/run/user/1000

    working_dir: /workspace/px4
    command: ["/bin/bash", "/entrypoint.sh"]
    networks:
      - drone_net

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ros2-vision:
    build:
      context: ./ros2
      dockerfile: Dockerfile
    container_name: ros2-vision
    stdin_open: true
    tty: true
    volumes:
      - ./ros2:/workspace/ros2
      - ./models:/workspace/ml_models
    working_dir: /workspace/ros2
    command: bash
    networks:
      - drone_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  microxrce-agent:
    build:
      context: ./microxrce-agent
      dockerfile: Dockerfile
    container_name: microxrce-agent
    stdin_open: true
    tty: true
    command: ["MicroXRCEAgent", "udp4", "-p", "8888"]
    networks:
      - drone_net

networks:
  drone_net:
    driver: bridge
